[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cheerlights"
version = "0.1.0"
description = "A Python package to interact with the CheerLights API via ThingSpeak."
